name: Build and deploy docs

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches: [ 'master' ]
    paths:
      - '.github/workflows/build-deploy-docs.yml'
      - 'docs/**'

jobs:
  build-and-deploy-docs:
    name: Build and Deploy Jupyter Book
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Conda environment
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: environment.yml
          extra-specs: |
            python=3.11

      - name: Create Jupyter kernelspec
        run: |
          python -m ipykernel install --user --name wrfotron --display-name "wrfotron"

      - name: Build Jupyter Book
        run: |
          jupyter-book build docs

      - name: Deploy the book's HTML to GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.9.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
